class Truck():
    def state(self):
        data = [
            {
            'vehicle_number':'CA221',
            'distance':1,
            'head':'L'
            },
            {
            'vehicle_number':'CA222',
            'distance':3,
            'head':'L'
            },
            {
            'vehicle_number':'CA223',
            'distance':5,
            'head':'L'
            },
            {
            'vehicle_number':'CA224',
            'distance':7,
            'head':'L'
            },
            {
            'vehicle_number':'CA225',
            'distance':9,
            'head':'L'
            },
            {
            'vehicle_number':'CA226',
            'distance':9,
            'head':'D'
            },
            {
            'vehicle_number':'CA227',
            'distance':7,
            'head':'D'
            },
            {
            'vehicle_number':'CA228',
            'distance':5,
            'head':'D'
            },
            {
            'vehicle_number':'CA229',
            'distance':3,
            'head':'D'
            },
            {
            'vehicle_number':'CA230',
            'distance':1,
            'head':'D'
            }
        ]
        return data